spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@jennyboo_high?TNS_ADMIN=C:/jennyboo/Spring/resource/Wallet_jennyboo
    username: admin
    password: Janepyo1994@@


  devtools:

    livereload:

      enabled: true

    thymeleaf:

      cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: jeynpyo@gmail.com
    password: jane1994!@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#server:
#  port: 8080
#security:
#  user:
#    name: user
#    password: 1234
#
#jpa:
#  hibernate:
#    ddl-auto: update
#  properties:
#    hibernate:
#      format_sql: true
#      show_sql: true
#
#profiles:
#  include: security